### ISSUE TITLE
deploy出错

### ISSUE THREAD

**Issue by wanghaisheng** [fengluo/fibos-todomvc#2]
好奇怪
/Users/wanghaisheng/workspace/fibos/fibos-todomvc/scripts/deploy.js:22:19
const jsCode = fs.readTextFile('../contracts/todo.js');
                  ^
Error: [2] No such file or directory
    at /Users/wanghaisheng/workspace/fibos/fibos-todomvc/scripts/deploy.js:22:19
npm ERR! code ELIFECYCLE

**Comment by fengluo** [comment]
已修复
